### ISSUE TITLE
安装错误

### ISSUE THREAD

**Issue by linwr1991** [nowa-webpack/nowa#1]
win7操作系统执行nowa install 提示没有install命令！
![1.jpg](https://gw.alicdn.com/tfscom/TB1zJTaKpXXXXXdaXXXXXXXXXXX)

**Comment by gbk** [comment]
和 resolve 模块有关，在 windwos 下无法正确解析路径，待排查。

**Comment by gbk** [comment]
使用 候选路径参数 paths 替换 候选目录参数 moduleDirectory 可以解决 windows 下的问题。

fixed at v0.1.5
