### ISSUE TITLE
nowa init page的时候，提示输入component name

### ISSUE THREAD

**Issue by fengsx** [nowa-webpack/nowa#15]
`nowa init page`的时候，提示输入`Component name`,其实应该是`Page name`啊
![page-component](https://cloud.githubusercontent.com/assets/7709602/17615645/2f9936fc-60a2-11e6-8816-e1b34c7fbf7d.png)

**Comment by gbk** [comment]
文案问题，稍后修正

**Comment by gbk** [comment]
fixed at v1.0.3

**Comment by yukap6** [comment]
nice
