### ISSUE TITLE
Error: EACCES: permission denied

### ISSUE THREAD

**Issue by summerinsect** [nowa-webpack/nowa#16]
Installing nowa-init ...
Error: EACCES: permission denied, symlink '../../../../Users/admin/.nowa/install/nowa-init/1.0.2/nowa-init' -> '/usr/local/lib/node_modules/nowa-init'
    at Error (native)
[rimraf@2.5.4] link /Users/admin/.nowa/install/.bin/rimraf@ -> ../rimraf/2.5.4/rimraf/bin.js

**Comment by summerinsect** [comment]
Solved：
sudo chown -R $USER /usr/local/

**Comment by gbk** [comment]
:+1:
