### ISSUE TITLE
ERROR in Cannot find module 'babel-core'

### ISSUE THREAD

**Issue by summerinsect** [nowa-webpack/nowa#17]
nowa server 之后，
js 都加载不出来。

webpack built 791893b0f522be7c200b in 458ms
Hash: 791893b0f522be7c200b
Version: webpack 1.13.2
Time: 458ms
  Asset    Size  Chunks       Chunk Names
 app.js  252 kB       0       app
demo.js  252 kB       1       demo

ERROR in Cannot find module 'babel-core'
 @ multi app

ERROR in Cannot find module 'babel-core'
 @ multi demo
webpack: bundle is now VALID.

**Comment by summerinsect** [comment]
npm install bable-core --save
But to no avail.

**Comment by summerinsect** [comment]
npm install babel-core
也没有用

**Comment by gbk** [comment]
Something go wrong when you install nowa. So please reinstall nowa.

```
sudo npm uninstall nowa -g
sudo npm i nowa -g --registry=https://registry.npm.taobao.org
nowa install --registry=https://registry.npm.taobao.org
```

**Comment by summerinsect** [comment]
重装了很多次，安装过程也没有报错，还是不行。

npm i nowa -g
/Users/admin/.nvm/versions/node/v4.4.7/bin/nowa -> /Users/admin/.nvm/versions/node/v4.4.7/lib/node_modules/nowa/index.js
/Users/admin/.nvm/versions/node/v4.4.7/lib
└─┬ nowa@1.0.6
  ├─┬ chalk@1.1.3
  │ ├── ansi-styles@2.2.1
  │ ├── escape-string-regexp@1.0.5
  │ ├─┬ has-ansi@2.0.0
  │ │ └── ansi-regex@2.0.0
  │ ├── strip-ansi@3.0.1
  │ └── supports-color@2.0.0
  ├─┬ commander@2.9.0
  │ └── graceful-readlink@1.0.1
  ├─┬ nowa-install@1.0.2
  │ ├── co@4.6.0
  │ └─┬ npminstall@1.14.2
  │   ├── await-event@1.0.0
  │   ├── binary-mirror-config@1.1.0
  │   ├── bytes@2.4.0
  │   ├─┬ cmd-shim@2.0.2
  │   │ └── graceful-fs@4.1.6
  │   ├─┬ co-fs-extra@1.2.1
  │   │ ├─┬ co-from-stream@0.0.0
  │   │ │ └── co-read@0.0.1
  │   │ ├─┬ fs-extra@0.26.7
  │   │ │ ├── jsonfile@2.3.1
  │   │ │ └── klaw@1.3.0
  │   │ └─┬ thunkify-wrap@1.0.4
  │   │   └── enable@1.3.2
  │   ├─┬ co-parallel@1.0.0
  │   │ └── co-thread@0.0.1
  │   ├── debug@2.2.0
  │   ├── destroy@1.0.4
  │   ├── minimist@1.2.0
  │   ├── ms@0.7.1
  │   ├─┬ mz@2.4.0
  │   │ ├── any-promise@1.3.0
  │   │ └─┬ thenify-all@1.6.0
  │   │   └── thenify@3.2.0
  │   ├─┬ node-gyp@3.4.0
  │   │ ├── fstream@1.0.10
  │   │ ├─┬ nopt@3.0.6
  │   │ │ └── abbrev@1.0.9
  │   │ ├─┬ npmlog@3.1.2
  │   │ │ ├─┬ are-we-there-yet@1.1.2
  │   │ │ │ └── delegates@1.0.0
  │   │ │ ├── console-control-strings@1.1.0
  │   │ │ ├─┬ gauge@2.6.0
  │   │ │ │ ├── aproba@1.0.4
  │   │ │ │ ├── has-color@0.1.7
  │   │ │ │ ├── has-unicode@2.0.1
  │   │ │ │ ├── signal-exit@3.0.0
  │   │ │ │ └── wide-align@1.1.0
  │   │ │ └── set-blocking@2.0.0
  │   │ ├─┬ osenv@0.1.3
  │   │ │ ├── os-homedir@1.0.1
  │   │ │ └── os-tmpdir@1.0.1
  │   │ ├─┬ path-array@1.0.1
  │   │ │ └─┬ array-index@1.0.0
  │   │ │   └─┬ es6-symbol@3.1.0
  │   │ │     ├── d@0.1.1
  │   │ │     └─┬ es5-ext@0.10.12
  │   │ │       └── es6-iterator@2.0.0
  │   │ ├─┬ request@2.74.0
  │   │ │ ├── aws-sign2@0.6.0
  │   │ │ ├── aws4@1.4.1
  │   │ │ ├─┬ bl@1.1.2
  │   │ │ │ └── readable-stream@2.0.6
  │   │ │ ├── caseless@0.11.0
  │   │ │ ├─┬ combined-stream@1.0.5
  │   │ │ │ └── delayed-stream@1.0.0
  │   │ │ ├── extend@3.0.0
  │   │ │ ├── forever-agent@0.6.1
  │   │ │ ├─┬ form-data@1.0.0-rc4
  │   │ │ │ └── async@1.5.2
  │   │ │ ├─┬ har-validator@2.0.6
  │   │ │ │ └─┬ is-my-json-valid@2.13.1
  │   │ │ │   ├── generate-function@2.0.0
  │   │ │ │   ├─┬ generate-object-property@1.2.0
  │   │ │ │   │ └── is-property@1.0.2
  │   │ │ │   ├── jsonpointer@2.0.0
  │   │ │ │   └── xtend@4.0.1
  │   │ │ ├─┬ hawk@3.1.3
  │   │ │ │ ├── boom@2.10.1
  │   │ │ │ ├── cryptiles@2.0.5
  │   │ │ │ ├── hoek@2.16.3
  │   │ │ │ └── sntp@1.0.9
  │   │ │ ├─┬ http-signature@1.1.1
  │   │ │ │ ├── assert-plus@0.2.0
  │   │ │ │ ├─┬ jsprim@1.3.0
  │   │ │ │ │ ├── extsprintf@1.0.2
  │   │ │ │ │ ├── json-schema@0.2.2
  │   │ │ │ │ └── verror@1.3.6
  │   │ │ │ └─┬ sshpk@1.9.2
  │   │ │ │   ├── asn1@0.2.3
  │   │ │ │   ├── assert-plus@1.0.0
  │   │ │ │   ├─┬ dashdash@1.14.0
  │   │ │ │   │ └── assert-plus@1.0.0
  │   │ │ │   ├── ecc-jsbn@0.1.1
  │   │ │ │   ├─┬ getpass@0.1.6
  │   │ │ │   │ └── assert-plus@1.0.0
  │   │ │ │   ├── jodid25519@1.0.2
  │   │ │ │   ├── jsbn@0.1.0
  │   │ │ │   └── tweetnacl@0.13.3
  │   │ │ ├── is-typedarray@1.0.0
  │   │ │ ├── isstream@0.1.2
  │   │ │ ├── json-stringify-safe@5.0.1
  │   │ │ ├─┬ mime-types@2.1.11
  │   │ │ │ └── mime-db@1.23.0
  │   │ │ ├── oauth-sign@0.8.2
  │   │ │ ├── qs@6.2.1
  │   │ │ ├── stringstream@0.0.5
  │   │ │ ├── tough-cookie@2.3.1
  │   │ │ └── tunnel-agent@0.4.3
  │   │ └─┬ which@1.2.10
  │   │   └── isexe@1.1.2
  │   ├── node-uuid@1.4.7
  │   ├─┬ npm-package-arg@4.2.0
  │   │ └── hosted-git-info@2.1.5
  │   ├── rimraf@2.5.4
  │   ├── runscript@1.1.0
  │   ├─┬ tar@2.2.1
  │   │ └── block-stream@0.0.9
  │   ├─┬ urllib@2.13.0
  │   │ ├─┬ default-user-agent@1.0.0
  │   │ │ └─┬ os-name@1.0.3
  │   │ │   ├── osx-release@1.1.0
  │   │ │   └── win-release@1.1.1
  │   │ ├─┬ digest-header@0.0.1
  │   │ │ └─┬ utility@0.1.11
  │   │ │   └── address@1.0.0
  │   │ ├── humanize-ms@1.2.0
  │   │ ├── iconv-lite@0.4.13
  │   │ ├── media-typer@0.3.0
  │   │ └── statuses@1.3.0
  │   ├─┬ utility@1.8.0
  │   │ ├── copy-to@2.0.1
  │   │ └── escape-html@1.0.3
  │   └── uuid@2.0.2
  ├─┬ nowa-plugin@1.1.0
  │ ├── ejs@2.4.2
  │ ├─┬ git-config@0.0.7
  │ │ └── iniparser@1.0.5
  │ ├─┬ glob@7.0.5
  │ │ ├── fs.realpath@1.0.0
  │ │ ├─┬ inflight@1.0.5
  │ │ │ └── wrappy@1.0.2
  │ │ ├── inherits@2.0.1
  │ │ ├─┬ minimatch@3.0.3
  │ │ │ └─┬ brace-expansion@1.1.6
  │ │ │   ├── balanced-match@0.4.2
  │ │ │   └── concat-map@0.0.1
  │ │ ├── once@1.3.3
  │ │ └── path-is-absolute@1.0.0
  │ ├─┬ inquirer@1.0.3
  │ │ ├── ansi-escapes@1.4.0
  │ │ ├─┬ cli-cursor@1.0.2
  │ │ │ └─┬ restore-cursor@1.0.1
  │ │ │   ├── exit-hook@1.1.1
  │ │ │   └── onetime@1.1.0
  │ │ ├── cli-width@2.1.0
  │ │ ├── figures@1.7.0
  │ │ ├── lodash@4.15.0
  │ │ ├── mute-stream@0.0.6
  │ │ ├─┬ pinkie-promise@2.0.1
  │ │ │ └── pinkie@2.0.4
  │ │ ├─┬ run-async@2.2.0
  │ │ │ └── is-promise@2.1.0
  │ │ ├── rx@4.1.0
  │ │ ├─┬ string-width@1.0.2
  │ │ │ ├─┬ code-point-at@1.0.0
  │ │ │ │ └── number-is-nan@1.0.0
  │ │ │ └── is-fullwidth-code-point@1.0.0
  │ │ └── through@2.3.8
  │ └─┬ mkdirp@0.5.1
  │   └── minimist@0.0.8
  ├─┬ package-json@2.3.3
  │ ├─┬ got@5.6.0
  │ │ ├─┬ create-error-class@3.0.2
  │ │ │ └── capture-stack-trace@1.0.0
  │ │ ├── duplexer2@0.1.4
  │ │ ├── is-plain-obj@1.1.0
  │ │ ├── is-redirect@1.0.0
  │ │ ├── is-retry-allowed@1.1.0
  │ │ ├── is-stream@1.1.0
  │ │ ├── lowercase-keys@1.0.0
  │ │ ├── node-status-codes@1.0.0
  │ │ ├── object-assign@4.1.0
  │ │ ├─┬ parse-json@2.2.0
  │ │ │ └─┬ error-ex@1.3.0
  │ │ │   └── is-arrayish@0.2.1
  │ │ ├── read-all-stream@3.1.0
  │ │ ├─┬ readable-stream@2.1.5
  │ │ │ ├── buffer-shims@1.0.0
  │ │ │ ├── core-util-is@1.0.2
  │ │ │ ├── isarray@1.0.0
  │ │ │ ├── process-nextick-args@1.0.7
  │ │ │ ├── string_decoder@0.10.31
  │ │ │ └── util-deprecate@1.0.2
  │ │ ├── timed-out@2.0.0
  │ │ ├── unzip-response@1.0.0
  │ │ └─┬ url-parse-lax@1.0.0
  │ │   └── prepend-http@1.0.4
  │ ├─┬ rc@1.1.6
  │ │ ├── deep-extend@0.4.1
  │ │ ├── ini@1.3.4
  │ │ └── strip-json-comments@1.0.4
  │ └── registry-url@3.1.0
  ├── resolve@1.1.7
  └── semver@5.1.1

**Comment by gbk** [comment]
加一步清缓存再试试呢？因为我们在各种情况下都没法重现你的问题，很有可能是网络原因造成的 npm 模块丢失。

sudo npm uninstall nowa -g
sudo npm cache clean
sudo rm -rf ~/.nowa ~/.npminstall_tarball
sudo npm i nowa -g --registry=https://registry.npm.taobao.org
sudo chmod 777 `npm root -g`
nowa install --registry=https://registry.npm.taobao.org

**Comment by summerinsect** [comment]
还是没有用，不过谢谢你们，以后重现问题了通知我。

**Comment by gbk** [comment]
是否可以换一台设备尝试一下呢？

**Comment by summerinsect** [comment]
解决了，我把nvm、node、nowa全部删了重装。。。

**Comment by gbk** [comment]
还是怀疑和 npm 模块缓存有关系，很抱歉给你造成这么多麻烦，后续我会想办法减少对 npm 的依赖

**Comment by yan513683375** [comment]
怎么清npm缓存呢，暴力破拆nvm，node太极端了吧= =、我也是他同样的bug。

**Comment by gbk** [comment]
@yan513683375 
```
sudo npm uninstall nowa -g
sudo npm cache clean
sudo rm -rf ~/.nowa ~/.npminstall_tarball
sudo npm i nowa -g --registry=https://registry.npm.taobao.org
sudo chmod 777 npm root -g
nowa install --registry=https://registry.npm.taobao.org
```
