### ISSUE TITLE
ERROR in Cannot find module 'babel-core'

### ISSUE THREAD

**Issue by wflashy** [nowa-webpack/nowa#19]
执行
npm install
nowa server

报错：
ERROR in Cannot find module 'babel-core'

具体信息如下：
Listening at http://192.168.1.110:3000
webpack built 8e87e450e4cd927f1d7c in 276ms
Hash: 8e87e450e4cd927f1d7c
Version: webpack 1.13.2
Time: 276ms
 Asset    Size  Chunks       Chunk Names
app.js  252 kB       0       app

ERROR in Cannot find module 'babel-core'
 @ multi app
webpack: bundle is now VALID.

**Comment by gbk** [comment]
npm 安装过程出现问题了，你试下是否能按照这个回复来解决？
https://github.com/nowa-webpack/nowa/issues/17#issuecomment-242040740

**Comment by wflashy** [comment]
谢谢！按照此方法，问题已解决。

sudo npm uninstall nowa -g
sudo npm cache clean
sudo rm -rf ~/.nowa ~/.npminstall_tarball
sudo npm i nowa -g --registry=https://registry.npm.taobao.org
sudo chmod 777  `npm root -g`
nowa install --registry=https://registry.npm.taobao.org

**Comment by gbk** [comment]
很抱歉给你造成不好的体验，相信随着 npm 的稳定性不断提高，这样的问题能更少出现……
