### ISSUE TITLE
windows10 64位下，执行nowa init报错

### ISSUE THREAD

**Issue by xcchcaptain** [nowa-webpack/nowa#2]
![image](https://cloud.githubusercontent.com/assets/5080022/16298005/d9f34bb0-3965-11e6-929f-15cc5c4879a4.png)
node :4.4.3
npm:3.8.7

**Comment by gbk** [comment]
[npminstall](https://github.com/cnpm/npminstall) 的问题，有部分模块下载失败。请尝试删除这个目录（ C:\Users\Administrator\AppData\Roaming\npm\node_modules\.npminstall ），然后重新执行安装命令：

```
nowa install
```
