### ISSUE TITLE
我是linux新手,nowa的权限很头疼呀

### ISSUE THREAD

**Issue by xttianma** [nowa-webpack/nowa#23]
1. 在centos上面,我解决不了非root的用户登录的权限问题,安装node和npm在默认位置,权限管辖很厉害. 
sudo 命令不和ubuntu一样. 安装使用不成. 换ubuntu系统才能安装顺利了. 

2. git hook 配置也是权限问题.

**Comment by gbk** [comment]
1. 不一定非得用 root 安装，也可以安装到项目目录下，在项目的 package.json 中增加以下配置：
```
"scripts": {
  "server": "nowa server",
  "build": "nowa build"
},
"devDependencies": {
  "nowa": "^1",
  "nowa-build": "^1",
  "nowa-server": "^1"
}
```
然后使用 `npm run server` 和 `npm run build` 来替代 `nowa server` 和 `nowa build` 命令即可。

2. git hook 具体什么问题我不是很清楚，你可以将软件安装到你有权限的目录即可。
