### ISSUE TITLE
build “salt-ui-master”  报错

### ISSUE THREAD

**Issue by xiegqooo** [nowa-webpack/nowa#24]
nowa build “salt-ui-master”（https://github.com/saltjs/salt-ui） 报错如下，求解决 。

ERROR in ./src/pages/scene/PageScene.styl
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (C:\Users\Administrator.nowa\install\extract-text-webpack-plugin\1.0.1\extract-text-webpack-plugin\loader.js:21:9)
 @ ./src/pages/scene/PageScene.js 11:0-27

**Comment by gbk** [comment]
这两个 issue 你看下是否能解决你的问题：
- https://github.com/webpack/extract-text-webpack-plugin/issues/50
- https://github.com/webpack/extract-text-webpack-plugin/issues/173
从大家的评论看至今没有发现确切的原因。。。

请检查：
1. 你的 nodejs 版本（推荐使用 v4.x）
2. 你项目中是否有覆盖 webpack.config.js（如果有的话，去掉再试试）

**Comment by xiegqooo** [comment]
问题已解决 。非常感谢 。 因为 node 版本过高 。 报错
