### ISSUE TITLE
demo中数据展示问题

### ISSUE THREAD

**Issue by waitliu** [nowa-webpack/nowa#25]
通过<p>{JSON.stringify(this.state)}</p> 数据被不知什么情况被放在demo中了。

页面实际的数据是{"loaded":false,"content":{},"error":false,"**_demo_**":{"loaded":true,"content":{"list":[{"workNo":"1234","name":"王小虎","nickName":"小虎"},{"workNo":"1357","name":"张小丽","nickName":"小丽"},{"workNo":"1728","name":"孙大圣","nickName":"大圣"}]},"error":false}}

但是只有{"loaded":true,"content":{"list":[{"workNo":"1234","name":"王小虎","nickName":"小虎"},{"workNo":"1357","name":"张小丽","nickName":"小丽"},{"workNo":"1728","name":"孙大圣","nickName":"大圣"}]},"error":false}才可以正常显示列表。

后端开发这一系列js技术真的搞不明白，还有各个版本的差别。

**Comment by gbk** [comment]
reflux 0.4.x 系列和 0.3.x 系列的差异之一就是前者会把数据放到绑定的 key 中
`reactMixin.onClass(Page, Reflux.connect(Store, 'demo'));`
所以解决问题的办法：要么把 reflux 版本降到 0.3.x，要么把业务逻辑改下从 demo 中拿数据。

这个问题在新版本的 salt 模板中修复。你可以重新初始化项目试试。
