### ISSUE TITLE
nowa server 报错 error in cannot find module babel-core

### ISSUE THREAD

**Issue by qhj1990** [nowa-webpack/nowa#26]
开发钉钉微应用项目时，使用nowa构建工具。按照文档一步一步，到了nowa server 报错：error in cannot find module babel-core。  npm install babel-core --save-dev 也没用。
nowa是否需要要编写webpack.config.js?

**Comment by qhj1990** [comment]
换台电脑没有这个问题。webpack.config.js nowa会默认生成

**Comment by gbk** [comment]
是 npm 安装的问题
