### ISSUE TITLE
nowa 打包后的css里图片路径有问题，

### ISSUE THREAD

**Issue by qhj1990** [nowa-webpack/nowa#27]
比如background-image：（/fhdsufhdhsfdsifhsdo.png）前面会有一个/多出来

**Comment by gbk** [comment]
fixed
`nowa install build` 或 `npm install nowa-build -g`
更新 nowa-build 到 v1.7.0 （`nowa` 查看插件版本）
试一下，是否能解决你的问题？

**Comment by qhj1990** [comment]
已经可以了

**Comment by linwr1991** [comment]
v1.9.0版本又 出现这个问题了

**Comment by gbk** [comment]
@linwr1991 你更新失败了，请尝试删除 ~/.nowa 目录，然后再重装 nowa
