### ISSUE TITLE
nowa build后console语句没有了的问题？

### ISSUE THREAD

**Issue by xiasf** [nowa-webpack/nowa#31]
为什么nowa build后，模块里面的console.log('str')这样的语句都没有了，难道生成是自动去除了吗？nowa server时控制台可以打印，但是生成的app.js里面控制台语句全部没有了，这是怎么回事？

**Comment by gbk** [comment]
是的，nowa build 的时候默认会去掉 console，避免一些不支持 console 的浏览器报错。
可以使用 nowa build --keepconsole 保留 console
