### ISSUE TITLE
支持vue构建

### ISSUE THREAD

**Issue by paseo** [nowa-webpack/nowa#33]
当前vue.js非常的流行，在中小型企业里，vue.js的使用率非常高。如果nowa支持vue.js的项目构建，有利于nowa的推广。

**Comment by gbk** [comment]
琢磨了半天，没搞定

1. 引入了 vue 全家桶，node_modules 大了 10M
2. vue-loader 内置了太多东西，不支持通过 query 给 babel-loader 传参（只能通过 babelrc，但是 nowa 不支持），导致 vue 模块里不能写 es6
3. vue-cli 功能足够强大易用，nowa 支持 vue 意义不大

later，暂放弃支持。
