### ISSUE TITLE
nowa init升级之后使用了refast，原先使用的是reflux，怎么办

### ISSUE THREAD

**Issue by WangYang-Rex** [nowa-webpack/nowa#48]
之前nowa init page出来的是reflux结构：
![image](https://cloud.githubusercontent.com/assets/7553998/26348385/2cff0f8a-3fdf-11e7-9a1a-8ffaf2bbdd23.png)

现在变成了refast
![image](https://cloud.githubusercontent.com/assets/7553998/26348348/0f09d960-3fdf-11e7-9ada-7058141e27e6.png)

请问怎么改回去？

**Comment by gbk** [comment]
你是通过 nowa 命令行还是图形界面来创建项目的呢？使用的是哪个脚手架？
@Jirapo @fengsx refast 应该都是在新分支上加的吧？老的脚手架没有动吧？

**Comment by Jirapo** [comment]
@gbk  nowa init page 应该增加一个选项是指定脚手架版本的

**Comment by gbk** [comment]
nowa init page 会读取 abc.json 的 template 字段来生成

**Comment by Jirapo** [comment]
@WangYang-Rex  可以检查你的abc.json 的template字段吗？
如果template字段是一个url地址，请修改成
mac: /Users/your_pc_name/.nowa-gui/template/nowa-template-salt-v_1
win: C:/Users/your_pc_name/.nowa-gui/template/nowa-template-salt-v_1

**Comment by WangYang-Rex** [comment]
问题是这样的，我本来的项目使用的v1，后面因为一些原因，abc.json里面的template并没有变https://github.com/nowa-webpack/template-salt/archive/master.zip，但是这个压缩包好像被改了

**Comment by Jirapo** [comment]
是的，目前salt有两个分支，master分支上默认的是v2分支，所以如果以后要使用v1版本的话，需要把master改为v1

**Comment by WangYang-Rex** [comment]
我并没有使用nowa-gui，而是用npm安装的nowa，请问这个要怎么解决，我并没有找到对应的v1版本文件

**Comment by WangYang-Rex** [comment]
用nowa init出来的项目，无论v1还是v2，abc.json里面的template好像都是
https://github.com/nowa-webpack/template-salt/archive/master.zip
这样好像会有问题

**Comment by Jirapo** [comment]
更改为 https://github.com/nowa-webpack/template-salt/archive/v2.zip

**Comment by WangYang-Rex** [comment]
之前的项目，更改为https://github.com/nowa-webpack/template-salt/archive/v1.zip，可以了，那我现在想用v1版本初始化一个新项目，需要怎么设置呢

**Comment by Jirapo** [comment]
nowa init https://github.com/nowa-webpack/template-salt/archive/v1.zip 
如果使用gui，会非常方便呢，不用输入一大串的地址

**Comment by WangYang-Rex** [comment]
可以了，之前是我搞错了

**Comment by WangYang-Rex** [comment]
恩，我试试gui...

**Comment by gbk** [comment]
@WangYang-Rex 搞定了么？

**Comment by WangYang-Rex** [comment]
@gbk 已经搞定了
