### ISSUE TITLE
now server cannot find module 'babel-core'

### ISSUE THREAD

**Issue by babycannotsay** [nowa-webpack/nowa#51]
这个问题我看了之前有人提过的，时间似乎是16年的9月，然后你们回答的。我试了一下还是不行。已经折腾了2个多小时了。求指教。

**Comment by babycannotsay** [comment]
最后到了npm/node_modules/nowa-server文件夹里把 node_modules删了，重新npm install居然就可以了。真的是npm的缓存问题吗？

**Comment by gbk** [comment]
确实是 npminstall 的问题
