### ISSUE TITLE
nowa能不能做到css主题化打包

### ISSUE THREAD

**Issue by WisestCoder** [nowa-webpack/nowa#55]
有一个项目，需要主题化（即有三份颜色不同的样式），我们现在的处理方法是打包后生成三个文件夹，每个文件夹下都有一份js和css，这样造成了打包过程十分缓慢，实际上三个文件夹下的js是一样的，区别只是css不同。所以我们希望打包过程中，能在代码压缩之前，把冗余的js删除。（~感觉主要的时间都浪费在代码压缩上，nowa也可以考虑使用[webpack-uglify-parallel](https://github.com/tradingview/webpack-uglify-parallel)来提升压缩速度）

**Comment by gbk** [comment]
建议收下了，在新的脚手架中会考虑你的需求，十月底上线。

现在如果想做的话，也可以，abc.json 里面配置 pages: true
./src/pages/green/index.js
./src/pages/blue/index.js
分别 require 自己的 css 文件

最后会输出 dist/green.css 和 dist/blue.css
