### ISSUE TITLE
npm i nowa -g报错，必现，急需解决

### ISSUE THREAD

**Issue by WangYang-Rex** [nowa-webpack/nowa#63]
<img width="767" alt="WX20190605-184002@2x" src="https://user-images.githubusercontent.com/7553998/58950621-c7adba00-87c1-11e9-86eb-fa8d01cae238.png">

目前执行 npm i nowa -g 时提示这个报错，安装不成功，感觉是esprima这个库版本更新的缘故，麻烦帮忙看下，急急急！

**Comment by gbk** [comment]
![image](https://user-images.githubusercontent.com/865717/59000368-be156800-883c-11e9-9b32-355a12a2e7de.png)
我这边试过没有问题啊，建议尝试卸载后重新安装：

```shell
rm -rf `npm root -g`/nowa
npm i nowa -g
```

或者请给出能还原你问题的更详细的信息
