### ISSUE TITLE
Module build failed

### ISSUE THREAD

**Issue by XueWenPeng** [nowa-webpack/nowa#64]
nowa server  error:
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/***/.nowa/install/_babel-preset-es2015@6.24.1@babel-preset-es2015/lib/index.js

**Comment by gbk** [comment]
nodejs 什么版本？

**Comment by XueWenPeng** [comment]
10.16.3


| |
dd
|
|
邮箱：15146529212@163.com
|

Signature is customized by Netease Mail Master

On 09/25/2019 13:56, gbk wrote:

nodejs 什么版本？

**Comment by gbk** [comment]
使用 nodejs 4.x 或 6.x，npm 3.x 重新安装试试看？
长久没有更新，可能部分依赖存在兼容性问题了

**Comment by XueWenPeng** [comment]
切node版本，最终提示我用6.x版本，我用6.x版本安装之后，init项目的时候，进度条卡在，fetchMetadata: sill mapToRegistry uri https://registry.npm.taobao.org/natty-fetch




| |
dd
|
|
邮箱：15146529212@163.com
|

Signature is customized by Netease Mail Master

On 09/26/2019 10:10, gbk wrote:

使用 nodejs 4.x 或 6.x，npm 3.x 重新安装试试看？
长久没有更新，可能部分依赖存在兼容性问题了

**Comment by XueWenPeng** [comment]
您有钉钉或者别的联系方式嘛，我加您一下




| |
dd
|
|
邮箱：15146529212@163.com
|

Signature is customized by Netease Mail Master

On 09/26/2019 10:17, XueWenPeng wrote:
切node版本，最终提示我用6.x版本，我用6.x版本安装之后，init项目的时候，进度条卡在，fetchMetadata: sill mapToRegistry uri https://registry.npm.taobao.org/natty-fetch




| |
dd
|
|
邮箱：15146529212@163.com
|

Signature is customized by Netease Mail Master

On 09/26/2019 10:10, gbk wrote:

使用 nodejs 4.x 或 6.x，npm 3.x 重新安装试试看？
长久没有更新，可能部分依赖存在兼容性问题了

**Comment by gbk** [comment]
加钉钉群 群号： 11769154
