### ISSUE TITLE
Require nodejs version ^4.0.0, current v6.2.1

### ISSUE THREAD

**Issue by bjliwei** [nowa-webpack/nowa#8]
Require nodejs version ^4.0.0, current v6.2.1
why ?

**Comment by yukap6** [comment]
@bjliwei  me too.
Rquire nodejs version ^4.0.0, current v6.2.2.  My solutions is uninstall nodejs and reinstall nodejs4.0.0. But the issue is still there, maybe the author can do something.

**Comment by gbk** [comment]
Since [this issue](https://github.com/shama/stylus-loader/issues/120) is still open, we can not support nodejs 6.x now.

If you really want to use nodejs 6.x, you can modify `nowa/package.json` `engines` field by yourself.
